// src/config/worlds.config.js
// 10 Cuboid Worlds for Grade 6 Mathematics (Singapore MOE Aligned)

export const WORLDS = [
  {
    id: 0,
    name: 'Box Basics Bay',
    emoji: '📦',
    accent: 'var(--world-0)',
    description: 'Count the cubes, then use the formula.',
    conceptFocus: 'volume-forward',
    boss: { name: 'Flat-Pack Phantom', emoji: '👻', reward: 'Box Basics Badge' },
  },
  {
    id: 1,
    name: 'Parcel Packing Plant',
    emoji: '🎁',
    accent: 'var(--world-1)',
    description: 'Real parcels, real units — cubic centimetres and cubic metres.',
    conceptFocus: 'volume-units',
    boss: { name: 'The Pile-Up', emoji: '🗃️', reward: 'Parcel Pro Badge' },
  },
  {
    id: 2,
    name: 'Base Area Bakery',
    emoji: '🧁',
    accent: 'var(--world-2)',
    description: 'Base area times height, and base area from length times breadth.',
    conceptFocus: 'base-area-forward',
    boss: { name: 'Baron Base-Area', emoji: '👑', reward: 'Base Builder Badge' },
  },
  {
    id: 3,
    name: 'Missing Height Hangar',
    emoji: '🏗️',
    accent: 'var(--world-3)',
    description: 'Height equals volume divided by base area.',
    conceptFocus: 'height-reverse',
    boss: { name: 'The Hollow Hangar', emoji: '🕳️', reward: 'Height Hunter Badge' },
  },
  {
    id: 4,
    name: 'Missing Edge Workshop',
    emoji: '🔧',
    accent: 'var(--world-4)',
    description: 'One dimension rubbed off — divide to get it back.',
    conceptFocus: 'dimension-reverse',
    boss: { name: 'The Edge Bandit', emoji: '🥷', reward: 'Edge Finder Badge' },
  },
  {
    id: 5,
    name: 'Face Finder Studio',
    emoji: '🪟',
    accent: 'var(--world-5)',
    description: 'Area of a face from the volume and perpendicular dimension.',
    conceptFocus: 'face-area-reverse',
    boss: { name: 'Faceless Frank', emoji: '🎭', reward: 'Face Finder Badge' },
  },
  {
    id: 6,
    name: 'Aquarium & Tank Lane',
    emoji: '🐠',
    accent: 'var(--world-6)',
    description: 'Water in rectangular tanks — millilitres, litres, and water depth.',
    conceptFocus: 'capacity-tank',
    boss: { name: 'Captain Overflow', emoji: '🌊', reward: 'Tank Tamer Badge' },
  },
  {
    id: 7,
    name: 'Stack & Store Yard',
    emoji: '🧱',
    accent: 'var(--world-7)',
    description: 'How many boxes fit inside a carton, and packing space.',
    conceptFocus: 'packing-multistep',
    boss: { name: 'The Stack Attacker', emoji: '🏋️', reward: 'Stack Master Badge' },
  },
  {
    id: 8,
    name: 'Compare & Decide Corner',
    emoji: '⚖️',
    accent: 'var(--world-8)',
    description: 'Which holds more, and by how much? Analytical comparisons.',
    conceptFocus: 'compare-reason',
    boss: { name: 'The Great Comparer', emoji: '🔍', reward: 'Sharp Reasoner Badge' },
  },
  {
    id: 9,
    name: 'Grand Depot Finale',
    emoji: '🏆',
    accent: 'var(--world-9)',
    description: 'Everything at once — multi-step depot challenges and depot mastery.',
    conceptFocus: 'mixed-review',
    boss: { name: 'Depot Dragon', emoji: '🐉', reward: 'Master of the Depot Badge' },
  },
];
